# Terminal AI - Provider Models Configuration

# OpenAI Models
openai:
  default: gpt-4o
  models:
    - name: GPT-4o
      value: gpt-4o
      pricing:
        input: 10.0 # Price per million tokens for input
        output: 30.0 # Price per million tokens for output
    - name: GPT-3.5 Turbo
      value: gpt-3.5-turbo
      pricing:
        input: 0.5 # Price per million tokens for input
        output: 1.5 # Price per million tokens for output

# Claude (Anthropic) Models
claude:
  default: claude-3-opus-20240229
  models:
    - name: Claude 3 Opus
      value: claude-3-opus-20240229
      pricing:
        input: 15.0 # Price per million tokens for input
        output: 75.0 # Price per million tokens for output
    - name: Claude 3 Sonnet
      value: claude-3-sonnet-20240229
      pricing:
        input: 3.0 # Price per million tokens for input
        output: 15.0 # Price per million tokens for output
    - name: Claude 3 Haiku
      value: claude-3-haiku-20240307
      pricing:
        input: 0.25 # Price per million tokens for input
        output: 1.25 # Price per million tokens for output

# Gemini (Google) Models
gemini:
  default: gemini-1.5-pro
  models:
    - name: Gemini 1.5 Pro
      value: gemini-1.5-pro
      pricing:
        input: 3.5 # Price per million tokens for input
        output: 10.5 # Price per million tokens for output
    - name: Gemini 1.5 Flash
      value: gemini-1.5-flash
      pricing:
        input: 0.35 # Price per million tokens for input
        output: 1.05 # Price per million tokens for output
    - name: Gemini 1.0 Pro
      value: gemini-1.0-pro
      pricing:
        input: 0.125 # Price per million tokens for input
        output: 0.375 # Price per million tokens for output

# Ollama Models
ollama:
  default: llama3
  models:
    - name: Llama 3
      value: llama3
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
    - name: Mistral
      value: mistral
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
    - name: Phi-3
      value: phi3
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
