# Terminal AI - Provider Models Configuration

# OpenAI Models
openai:
  default: gpt-4o
  models:
    - name: GPT-4o
      value: gpt-4o
    - name: GPT-3.5 Turbo
      value: gpt-3.5-turbo

# Claude (Anthropic) Models
claude:
  default: claude-3-opus-20240229
  models:
    - name: Claude 3 Opus
      value: claude-3-opus-20240229
    - name: Claude 3 Sonnet
      value: claude-3-sonnet-20240229
    - name: Claude 3 Haiku
      value: claude-3-haiku-20240307

# Gemini (Google) Models
gemini:
  default: gemini-1.5-pro
  models:
    - name: Gemini 1.5 Pro
      value: gemini-1.5-pro
    - name: Gemini 1.5 Flash
      value: gemini-1.5-flash
    - name: Gemini 1.0 Pro
      value: gemini-1.0-pro

# Ollama Models
ollama:
  default: llama3
  models:
    - name: Llama 3
      value: llama3
    - name: Mistral
      value: mistral
    - name: Phi-3
      value: phi3 