openai:
  default: gpt-4o
  models:
    - name: GPT-4o
      value: gpt-4o
      pricing:
        input: 10.0 # Price per million tokens for input
        output: 30.0 # Price per million tokens for output
    - name: GPT-3.5 Turbo
      value: gpt-3.5-turbo
      pricing:
        input: 0.5 # Price per million tokens for input
        output: 1.5 # Price per million tokens for output

ollama:
  default: llama3
  models:
    - name: Llama 3.2
      value: llama3.2
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
    - name: Mistral
      value: mistral
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
    - name: Phi-3
      value: phi3
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free
